### ISSUE TITLE
Support node 14

### ISSUE THREAD

**Issue by nite** [alex-okrushko/backoff-rxjs#22]
Hi, 

We've got this issue: 
```
error backoff-rxjs@6.5.6: The engine "node" is incompatible with this module. Expected version ">=10.9.0 <13.0.0". Got "14.2.0"
```

however I see no issue with backoff-rxjs and node 14 using: 
```
yarn config set ignore-engines true
```

Should you remove the upper restriction, until you come upon any issues? 
This is the only package I have this issue with when updating to node 14.

**Comment by alex-okrushko** [comment]
Thanks @nite you are right. I added jest instead of mocha/chai and the tests themselves had issues with node < 10 or > 12.
I tried limiting the node version by setting the engines, however that didn't help and finally I solved the issue by setting the specific node version for cloudbuild. 
All of that is needed for tests only, and doesn't affect the actual code, so dropping this restriction in `6.5.7`.

Thanks for opening the issue!
